
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.cunoc.Conexion;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ARCHIVO = 7;
  public static final int PARCLO = 10;
  public static final int SUCCESS = 8;
  public static final int MENORQUE = 2;
  public static final int SINTACTICO = 6;
  public static final int STRING = 11;
  public static final int EOF = 0;
  public static final int MAYORQUE = 4;
  public static final int LEXICO = 3;
  public static final int DIAGONAL = 5;
  public static final int error = 1;
  public static final int PAROP = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MENORQUE",
  "LEXICO",
  "MAYORQUE",
  "DIAGONAL",
  "SINTACTICO",
  "ARCHIVO",
  "SUCCESS",
  "PAROP",
  "PARCLO",
  "STRING"
  };
}

